car = 'subaru'
print("Is car == 'subaru'? I predict True.")
print(car == 'subaru')
print("\nIs car == 'audi'? I predict False.")
print(car == 'audi')
print("\nIs car == 'bmw'? I predict False.")
print(car == 'bmw')
print("\nIs car == 'toyota'? I predict False.")
print(car == 'toyota')
print("\nIs car.title() == 'Subaru'? I predict True.")
print(car.title() == 'Subaru')
print("\nIs car.upper() == 'SUBARU'? I predict True.")
print(car.upper() == 'SUBARU')

age = 23
print("\nIs age == 23? I predict True.")
print(age == 23)
print("\nIs age <= 20? I predict False.")
print(age <= 20)
print("\nIs age >= 20? I predict True.")
print(age >= 20)
print("\nIs age != 20? I predict True.")
print(age != 20)
print("\nIs age < 20? I predict False.")
print(age < 20)
print("\nIs age > 20? I predict True.")
print(age > 20)

