places = ['neelum valley','hunza valley','swat valley','kalash valley','kaghan valley']
print(places)
sorted_places = sorted(places)
print(sorted_places)
print(places)
reverse_sorted_places = sorted(places,reverse=True)
print(reverse_sorted_places)
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)